spring:
  application:
    name: aspect_oriented_programming
  datasource:
    url: jdbc:h2:mem:aopdb
    username: aop
    password: password
    driverClassName: org.h2.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: embedded
